---
# tasks file for ansible-role

- name: Prepare enviroment
  include_tasks:
    file: "prepare.yml"
  args:
    apply:
      delegate_to: localhost
  tags:
    - prepare
    - sombackoffice

- name: Run backoffice tasks
  include_tasks:
    file: "backoffice.yml"
  args:
    apply:
      delegate_to: localhost
  tags:
    - build
    - sombackoffice

- name: Upload new version
  include_tasks:
    file: "upload.yml"
  tags:
    - upload
    - sombackoffice
