---
- name: Ensure base path exists
  ansible.builtin.file:
    path: "{{ somoffice_remote_base_path }}"
    state: directory
    mode: 0755
  tags:
    - sombackoffice
    - deploy

- name: Ensure rsync is available
  ansible.builtin.apt:
    name: rsync
    state: present
    update_cache: true
  tags:
    - sombackoffice
    - deploy

- name: Ensure deploy folder exists
  ansible.builtin.file:
    path: "{{ somoffice_role_deploy_path }}"
    state: directory
    mode: 0755
  tags:
    - sombackoffice
    - deploy

- name: Upload the build folder to new created folder in server.
  ansible.posix.synchronize:
    src: "{{ somoffice_role_local_path }}/src/"
    dest: "{{ somoffice_role_deploy_path }}"
    recursive: true
    delete: true
  notify: "Remove temporal folder"
  tags:
    - sombackoffice
    - deploy
